server:
  port: 87
  servlet:
    context-path: /file
spring:
  application:
    name: file-server
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
minio:
  access-key: admin
  endpoint-url: http://localhost:9000
  bucket-name: gmall
  secre-key: 12345678