my-server:
  addr: localhost

spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: ${my-server.addr}:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        shared-configs:
          - data-id: common.yaml
            refresh: true




